import os
from time import sleep

os.system("clear")
print(f"C"),sleep(0.5),print(f" O"),sleep(0.5),print(f"  O"),sleep(0.5),print(f"   L"),sleep(0.5),print(f"    -"),sleep(0.5),print(f"     H"),sleep(0.5),print(f"      A"),sleep(0.5),print(f"       C"),sleep(0.5),print(f"        K"),sleep(0.5),print(f"         E"),sleep(0.5),print(f"          R"),sleep(0.5),print(f"           S"),sleep(0.5)
print(f"\t\t\tДанный код является просто установщиком нужных утилит и пакетов для базы Android и на IOS, НО никак не на Windows")
print("Вы точно хотите начать установку? ")
start_input = input(">>> ")
if str(start_input) == "n":
    print("Данный код выключается")
    sleep(0.75)
    os.system("clear")
    print(f"\t\t\tКод написан им ---> https://vk.com/nikitasos1ska")
    print(f"\t\t\tТе кто присоединён к Cool-Hackers ---> https://vk.com/nikitasos1ska, https://vk.com/paket20, https://vk.com/covidone, https://vk.com/2pac_jdm")
    print(f"\t\t\tНаши Git профили --> https://github.com/Sos1ska, https://github.com/Ki11sesh, https://github.com/Cool-Hackers")
    quit()

input("Начать установку Хакерский утилит? ")
print("Начинаю проверку обновлений")
mod = ("update", "upgrade")
for i in range(len(mod)):
    print("Проверка...")
    os.system("apt "+mod[i]+"...")
    os.system("clear")
    print("Проверка завершена")
    os.system("clear")
print("Обновление Pip")
os.system("pip install --upgrade pip")
os.system("clear")
mod = ("requests", "urllib3")
input("Нажмите Enter для установки комопнентов Pip")
print("Начинаю установку через Pip")
for i in range(len(mod)):
    print("Установка "+mod[i]+"...")
    os.system("pip install "+mod[i])
    os.system("clear")

print("Установка комопнентов Pip завершено")
sleep(0.75)
os.system("clear")
print("Начинаю установку нужных пакетов")
os.system("pkg install git -y")
os.system("pkg install tor -y")
os.system("pkg install root-repo -y")
os.system("pkg install unstable-repo -y")
os.system("pkg install x11-repo -y")
os.system("pkg install cowsay -y")
os.system("pkg install toilet -y")
os.system("clear")
os.system("cd /data/data/com.termux/files/home/")
input("Нажмите Enter для установки через пакет git")
print("Начинаю установку нужных утилит через git")
os.system("git clone https://github.com/Sos1ska/IP-System")
os.system("clear")
print("Какой установить вам код от Sos1ska или от Cool-Hackers? Для ответа введите S от Sos1ska, C от Cool-Hackers (Вводите на английской раскладке)")
cont_input = input(">>> ")
if str(cont_input) == "S", "s":
    os.system("git clone https://github.com/Sos1ska/Number-System")
    os.system("clear")
if str(cont_input) == "C", "c":
    os.system("git clone https://github.com/Cool-Hackers/Number-System")
    os.system("clear")
os.system("git clone https://github.com/Sos1ska/Sms-BomberSos1.0")
os.system("clear")
os.system("cd Number-System/Sos-Break/Termux/")
os.system("bash install.sh")
os.system("clear")
os.system("cd /data/data/com.termux/files/home/")
os.system("cowsay -f dragon 'Made Script By user: https://vk.com/nikitasos1ska' ")

print(f"\t\t\tКод написан им ---> https://vk.com/nikitasos1ska")
print(f"\t\t\tТе кто присоединён к Cool-Hackers ---> https://vk.com/nikitasos1ska, https://vk.com/paket20, https://vk.com/covidone, https://vk.com/2pac_jdm")
print(f"\t\t\tНаши Git профили --> https://github.com/Sos1ska, https://github.com/Ki11sesh, https://github.com/Cool-Hackers")