import os
input("Начать установку Хакерский утилит? ")
print("Начинаю проверку обновлений")
mod = ("update", "upgrade")
for i in range(len(mod)):
    print("Проверка...")
    os.system("apt "+mod[i]+"...")
    os.system("clear")
    print("Проверка завершена")
    os.system("clear")
print("Обновление Pip")
os.system("pip install --upgrade pip")
os.system("clear")
mod = ("html2tetx", "requests", "bs4", "vk_api", "urllib3")
input("Нажмите Enter для установки комопнентов Pip")
print("Начинаю установку через Pip")
for i in range(len(mod)):
    print("Установка "+mod[i]+"...")
    os.system("pip install "+mod[i])
    os.system("clear")
print("Установка комопнентов Pip завершено")
os.system("clear")
print("Начинаю установку нужных пакетов")
os.system("pkg install git -y")
os.system("pkg install tor -y")
os.system("pkg install root-repo -y")
os.system("pkg install unstable-repo -y")
os.system("pkg install x11-repo -y")
os.system("pkg install php")
os.system("pkg install cowsay -y")
os.system("pkg install toilet -y")
os.system("pkg install msfconsole -y")
os.system("clear")
print("Установка пакетов завершена")
os.system("cd $HOME")
input("Нажмите Enter для установки через пакет git")
print("Начинаю установку нужных утилит через git")
os.system("git clone https://github.com/SenTDI/Infinite-Bomber-android")
os.system("clear")
os.system("git clone https://github.com/maldevel/IPGeoLocation")
os.system("clear")
os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK")
os.system("clear")
os.system("git clone https://github.com/tchelospy/termux-ngrok.git")
os.system("clear")
os.system("git clone https://github.com/artem-cell/wifi-dosser")
os.system("clear")
os.system("git clone https://github.com/DataSC3/No-BlackM")
os.system("clear")
os.system("git clone https://github.com/websploit/websploit.git")
os.system("clear")
os.system("git clone https://github.com/Hydra7/Planetwork-DDOS")
os.system("clear")
os.system("git clone https://github.com/evait-security/weeman")
os.system("clear")
print("Установка нужных утилит завершена")
input("Вам помочь настроить утилиты? Если да, то нажмите на Enter!")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-arm/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-arm/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-arm64/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-arm64-without-tor/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-x64/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-x64-without-tor/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-x86/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("cd Infinite-Bomber-android/Infinite-Bomber-x86-without-tor/ && chmod 777 infinite-bomber")
os.system("cd $HOME")
os.system("clear")
os.system("cd IPGeoLocation/ chmod 777 ipgeolocation.py")
os.system("pip3 install -r requirements.txt")
os.system("cd $HOME")
os.system("clear")
os.system("cd RED_HAWK/ && chmod 777 rhawk.php")
os.system("cd $HOME")
os.system("clear")
os.system("cd termux-ngrok/ && chmod +x termux-ngrok.sh")
os.system("cd $HOME")
os.system("cd wifi-dosser/ && bash installer.sh")
os.system("cd $HOME")
os.system("cd websploit/ && python setup.py")
os.system("cd $HOME")
os.system("cowsay -f dragon 'Made Script By user: https://vk.com/nikitasos1ska' ")